version: '3.7'

services:
  app:
    build: .
    command: bash -c "cd app &&
      alembic upgrade head &&
      cd .. && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./app:/app/app
      - ./app/migration:/app/app/migration
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

#  bot:
#    build: .
#    command: bash -c "cd app && python3 bot/main.py"
#    network_mode: host
#    env_file:
#      - .env
#    environment:
#      - PYTHONPATH=/app

  db:
    image: mysql:8.2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=strong_password
      - MYSQL_DATABASE=peep
      - MYSQL_USER=peep
      - MYSQL_PASSWORD=password