version: '3.7'

services:
  app:
    build: .
    command: bash -c "cd app && alembic upgrade head && cd .. && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    network_mode: host
    env_file:
      - .env
    ports:
      - "8000:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
  bot:
    build: .
    command: bash -c "cd app && python3 bot/main.py"
    network_mode: host
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

