version: '3.7'

services:
  app:
    build: .
    command: bash -c "cd app && alembic upgrade head && cd .. && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
  bot:
    build: .
    command: bash -c "cd app && python3 bot/main.py"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
