"""initial

Revision ID: 17f1f5db08ce
Revises: 
Create Date: 2024-09-07 11:33:31.826305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f1f5db08ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('point', sa.String(length=128), nullable=True),
    sa.Column('key', sa.String(length=130), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_point'), 'point', ['point'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('count_photos', sa.Integer(), nullable=True),
    sa.Column('datetime_str', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('point', sa.String(length=128), nullable=True),
    sa.Column('session', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('count_photos_cloud', sa.Integer(), nullable=True),
    sa.Column('public_link', sa.String(length=512), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_point'), 'session', ['point'], unique=False)
    op.create_index(op.f('ix_session_status'), 'session', ['status'], unique=False)
    op.create_table('template',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('point', sa.String(length=128), nullable=True),
    sa.Column('subject', sa.String(length=128), nullable=True),
    sa.Column('template_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_point'), 'template', ['point'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_point'), table_name='template')
    op.drop_table('template')
    op.drop_index(op.f('ix_session_status'), table_name='session')
    op.drop_index(op.f('ix_session_point'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_point_point'), table_name='point')
    op.drop_table('point')
    # ### end Alembic commands ###
