"""rename_column

Revision ID: 985265890409
Revises: e98510c11ecb
Create Date: 2024-10-20 13:46:00.762853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '985265890409'
down_revision: Union[str, None] = 'e98510c11ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point', sa.Column('access_key', sa.String(length=130), nullable=True))
    op.drop_column('point', 'key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point', sa.Column('key', mysql.VARCHAR(length=130), nullable=True))
    op.drop_column('point', 'access_key')
    # ### end Alembic commands ###
