"""add_mobile_key

Revision ID: e98510c11ecb
Revises: 17f1f5db08ce
Create Date: 2024-10-19 23:22:22.251237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98510c11ecb'
down_revision: Union[str, None] = '17f1f5db08ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point', sa.Column('mobile_key', sa.String(length=130), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('point', 'mobile_key')
    # ### end Alembic commands ###
